//! Approval / baseline tests for `vti-core` against Pascal-generated fixtures.
//!
//! Each test loads a committed JSON fixture from
//! `tests/fixtures/pascal-baselines/` and asserts that the Rust
//! implementation produces bit-identical output.
//!
//! The fixtures were generated by running
//!   `bash pascal-tests/run_harness.sh`
//! which compiles `pascal-tests/vt_harness.pas` (FPC) and outputs JSON.
//!
//! HOW TO REGENERATE
//! -----------------
//! 1. Install fpc (Free Pascal ≥ 3.x).
//! 2. Run:  bash pascal-tests/run_harness.sh
//! 3. Review the diff and commit the updated fixtures.
//!
//! A change in a fixture file that was NOT caused by a deliberate Pascal
//! source change is a regression — investigate before merging.

use serde::Deserialize;
use vti_core::note_tables::{
    PT3_NOTE_TABLE_PT, PT3_NOTE_TABLE_ST, PT3_NOTE_TABLE_ASM,
    PT3_NOTE_TABLE_REAL, PT3_NOTE_TABLE_NATURAL,
};
use vti_core::note_tables::PT3_VOL;
use vti_core::playback::{Engine, PlayVars, init_tracker_parameters};
use vti_core::{
    AdditionalCommand, AyRegisters, ChannelLine, Module, Pattern,
    Sample, SampleTick,
};

// ─── Fixture types ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct PT3VolFixture {
    table: Vec<Vec<u8>>,
}

#[derive(Deserialize)]
struct NoteTablesFixture {
    tables: NoteTablesMap,
}

#[derive(Deserialize)]
struct NoteTablesMap {
    #[serde(rename = "PT")]
    pt: Vec<u16>,
    #[serde(rename = "ST")]
    st: Vec<u16>,
    #[serde(rename = "ASM")]
    asm: Vec<u16>,
    #[serde(rename = "REAL")]
    real: Vec<u16>,
    #[serde(rename = "NATURAL")]
    natural: Vec<u16>,
}

#[derive(Deserialize)]
struct PatternPlayFixture {
    delay: i8,
    ticks: Vec<TickRecord>,
}

#[derive(Deserialize)]
struct TickRecord {
    tick: usize,
    result: i32,
    current_line: usize,
    delay_counter: i8,
    regs: RegsRecord,
}

#[allow(dead_code)]
#[derive(Deserialize, Debug)]
struct RegsRecord {
    ton_a: u16,
    ton_b: u16,
    ton_c: u16,
    noise: u8,
    mixer: u8,
    ampl_a: u8,
    ampl_b: u8,
    ampl_c: u8,
    envelope: u16,
    env_type: u8,
}

// ─── Helper ──────────────────────────────────────────────────────────────────

fn load_core_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/pascal-baselines/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read fixture {}: {}", path, e))
}

/// Pascal result code → PlayResult:
///   0 = rendering (Updated), 1 = line advanced (Updated), 2 = PatternEnd
fn pascal_result_is_pattern_end(result: i32) -> bool {
    result == 2
}

// ─── PT3_Vol table ────────────────────────────────────────────────────────────

#[test]
fn pt3_vol_matches_pascal_baseline() {
    let raw = load_core_fixture("pt3_vol");
    let fixture: PT3VolFixture =
        serde_json::from_str(&raw).expect("parse pt3_vol.json");

    for (r, row) in fixture.table.iter().enumerate() {
        for (c, &expected) in row.iter().enumerate() {
            let got = PT3_VOL[r][c];
            assert_eq!(
                got, expected,
                "PT3_VOL[{}][{}]: got {}, want {}",
                r, c, got, expected
            );
        }
    }
}

// ─── Note tables ─────────────────────────────────────────────────────────────

/// Verify all five note tables match the Pascal constants verbatim.
#[test]
fn note_tables_match_pascal_baseline() {
    let raw = load_core_fixture("note_tables");
    let fixture: NoteTablesFixture =
        serde_json::from_str(&raw).expect("parse note_tables.json");

    let tables: &[(&str, &[u16; 96], &Vec<u16>)] = &[
        ("PT",      &PT3_NOTE_TABLE_PT,      &fixture.tables.pt),
        ("ST",      &PT3_NOTE_TABLE_ST,      &fixture.tables.st),
        ("ASM",     &PT3_NOTE_TABLE_ASM,     &fixture.tables.asm),
        ("REAL",    &PT3_NOTE_TABLE_REAL,    &fixture.tables.real),
        ("NATURAL", &PT3_NOTE_TABLE_NATURAL, &fixture.tables.natural),
    ];

    for (name, rust_table, pascal_table) in tables {
        assert_eq!(rust_table.len(), pascal_table.len(), "table {} length", name);
        for (i, (&got, &expected)) in rust_table.iter().zip(pascal_table.iter()).enumerate() {
            assert_eq!(
                got, expected,
                "table {} note {}: got {:#x}, want {:#x}",
                name, i, got, expected
            );
        }
    }
}

// ─── Pattern playback ─────────────────────────────────────────────────────────

/// Build the same module that the Pascal harness uses for pattern_basic:
///   4-row pattern, delay=3, note C-4 on row 0, pure-tone sample.
fn make_harness_module(with_envelope: bool) -> Module {
    let mut m = Module::default();
    m.initial_delay = 3;
    m.ton_table = 0; // PT table
    m.positions.length = 1;
    m.positions.value[0] = 0;

    // IsChans defaults: global_ton/noise/envelope = true, sample=1, volume=15
    for ch in 0..3 {
        m.is_chans[ch].global_ton = true;
        m.is_chans[ch].global_noise = true;
        m.is_chans[ch].global_envelope = true;
        m.is_chans[ch].envelope_enabled = false;
        m.is_chans[ch].sample = 1;
        m.is_chans[ch].volume = 15;
    }

    // Ornament 0: single step, zero offset
    // (already installed by Module::default())

    // Sample 1: 4 ticks, amplitude=15, mixer_ton=true (tone active),
    //           mixer_noise=false (noise muted)
    let mut sam = Sample::default();
    sam.length = 4;
    sam.loop_pos = 0;
    sam.enabled = true;
    for i in 0..4 {
        sam.items[i] = SampleTick {
            amplitude: 15,
            mixer_ton: true,    // tone NOT muted
            mixer_noise: false, // noise muted
            envelope_enabled: with_envelope,
            ..SampleTick::default()
        };
    }
    m.samples[1] = Some(Box::new(sam));

    // Pattern 0: 4 rows
    let mut pat = Pattern::default();
    pat.length = 4;

    // Row 0: note C-4 (36) on all channels, sample 1, volume 15
    for ch in 0..3 {
        pat.items[0].channel[ch] = ChannelLine {
            note: 36,
            sample: 1,
            volume: 15,
            ornament: 0,
            envelope: if with_envelope && ch == 0 { 8 } else { 0 },
            additional_command: AdditionalCommand::default(),
        };
    }
    if with_envelope {
        pat.items[0].envelope = 0x0800;
        m.is_chans[0].envelope_enabled = true;
    }

    // Rows 1-3: no note
    for row in 1..4 {
        for ch in 0..3 {
            pat.items[row].channel[ch].note = -1;
        }
    }

    m.patterns[0] = Some(Box::new(pat));
    m
}

fn run_pattern_play_baseline(fixture_name: &str, with_envelope: bool) {
    let raw = load_core_fixture(fixture_name);
    let fixture: PatternPlayFixture =
        serde_json::from_str(&raw).expect("parse fixture");

    let mut m = make_harness_module(with_envelope);
    let mut vars = PlayVars {
        current_pattern: 0,
        current_line: 0,
        delay: fixture.delay,
        delay_counter: 1,
        ..PlayVars::default()
    };
    init_tracker_parameters(&mut m, &mut vars, true);

    for expected_tick in &fixture.ticks {
        let line_before = vars.current_line;
        let mut regs = AyRegisters::default();
        let mut engine = Engine { module: &mut m, vars: &mut vars };
        let result = engine.pattern_play_current_line(&mut regs);

        // Map PlayResult to Pascal integer:
        //   PatternEnd = 2 (Pascal returns 2 when pattern length exceeded)
        //   Updated with line advance = 1 (delay_counter hit 0 and line processed)
        //   Updated without advance  = 0 (delay_counter still counting down)
        let got_result = match result {
            vti_core::playback::PlayResult::PatternEnd => 2,
            vti_core::playback::PlayResult::ModuleLoop  => 3,
            vti_core::playback::PlayResult::Updated     => {
                // A line was advanced this tick when current_line increased.
                if vars.current_line > line_before { 1 } else { 0 }
            }
        };

        // ── result code ──────────────────────────────────────────────────────
        assert_eq!(
            got_result, expected_tick.result,
            "tick {}: result mismatch (got {}, want {})",
            expected_tick.tick, got_result, expected_tick.result
        );

        // On PatternEnd the Pascal exits WITHOUT rendering registers, so we
        // cannot compare register values for those ticks.
        if pascal_result_is_pattern_end(expected_tick.result) {
            // Still check line / counter bookkeeping
            assert_eq!(
                vars.current_line, expected_tick.current_line,
                "tick {}: current_line mismatch on PatternEnd",
                expected_tick.tick
            );
            assert_eq!(
                vars.delay_counter, expected_tick.delay_counter,
                "tick {}: delay_counter mismatch on PatternEnd",
                expected_tick.tick
            );
            continue;
        }

        // ── AY register values ───────────────────────────────────────────────
        let e = &expected_tick.regs;
        assert_eq!(regs.ton_a,       e.ton_a,  "tick {}: ton_a",       expected_tick.tick);
        assert_eq!(regs.ton_b,       e.ton_b,  "tick {}: ton_b",       expected_tick.tick);
        assert_eq!(regs.ton_c,       e.ton_c,  "tick {}: ton_c",       expected_tick.tick);
        assert_eq!(regs.noise,       e.noise,  "tick {}: noise",       expected_tick.tick);
        assert_eq!(regs.mixer,       e.mixer,  "tick {}: mixer",       expected_tick.tick);
        assert_eq!(regs.amplitude_a, e.ampl_a, "tick {}: amplitude_a", expected_tick.tick);
        assert_eq!(regs.amplitude_b, e.ampl_b, "tick {}: amplitude_b", expected_tick.tick);
        assert_eq!(regs.amplitude_c, e.ampl_c, "tick {}: amplitude_c", expected_tick.tick);
        assert_eq!(regs.envelope,    e.envelope, "tick {}: envelope",  expected_tick.tick);

        // ── Playback state ───────────────────────────────────────────────────
        assert_eq!(
            vars.current_line, expected_tick.current_line,
            "tick {}: current_line",
            expected_tick.tick
        );
        assert_eq!(
            vars.delay_counter, expected_tick.delay_counter,
            "tick {}: delay_counter",
            expected_tick.tick
        );
    }
}

/// Pure-tone pattern: 4 rows, delay=3, note C-4. No envelope.
#[test]
fn pattern_play_basic_matches_pascal_baseline() {
    run_pattern_play_baseline("pattern_play_basic", false);
}

/// Same pattern but with AY envelope type 8 (sawtooth-down) on channel A.
#[test]
fn pattern_play_envelope_matches_pascal_baseline() {
    run_pattern_play_baseline("pattern_play_envelope", true);
}
