//! Approval / baseline tests for `vti-ay` against Pascal-generated fixtures.
//!
//! Each test loads a committed JSON fixture from
//! `tests/fixtures/pascal-baselines/` and asserts that the Rust
//! implementation produces bit-identical output.
//!
//! The fixtures were generated by running
//!   `bash pascal-tests/run_harness.sh`
//! which compiles `pascal-tests/vt_harness.pas` (FPC) and outputs JSON.
//! That Pascal code is a faithful port of S.V.Bulba's original AY.pas.
//!
//! HOW TO REGENERATE
//! -----------------
//! 1. Install fpc (Free Pascal ≥ 3.x).
//! 2. Run:  bash pascal-tests/run_harness.sh
//! 3. Review the diff and commit the updated fixtures.
//!
//! A change in a fixture file that was NOT caused by a deliberate Pascal
//! source change is a regression — investigate before merging.

use serde::Deserialize;
use vti_ay::chip::{noise_generator, ChipType, EnvShape, SoundChip};
use vti_ay::config::AyConfig;
use vti_ay::synth::calculate_level_tables;

// ─── Fixture types ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct NoiseLfsrFixture {
    initial_seed: u32,
    steps: Vec<NoiseLfsrStep>,
}

#[derive(Deserialize)]
struct NoiseLfsrStep {
    seed: u32,
    noise_val: u32,
}

#[derive(Deserialize)]
struct EnvelopeShapesFixture {
    shapes: Vec<EnvelopeShapeCase>,
}

#[derive(Deserialize)]
struct EnvelopeShapeCase {
    register_value: u8,
    name: String,
    initial_ampl: i32,
    steps: Vec<EnvelopeStep>,
}

#[derive(Deserialize)]
struct EnvelopeStep {
    ampl: i32,
    first_period: bool,
}

// ─── Helper ──────────────────────────────────────────────────────────────────

fn load_ay_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/pascal-baselines/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read fixture {}: {}", path, e))
}

// ─── Noise LFSR ──────────────────────────────────────────────────────────────

/// Verify that the Rust LFSR produces the same 200-step sequence as the Pascal.
///
/// The Pascal NoiseGenerator uses taps bit13 XOR bit16 of the 17-bit seed.
/// noise_val is bit16 of the resulting seed (from the packed-record union
/// layout in the original TSoundChip).
#[test]
fn noise_lfsr_matches_pascal_baseline() {
    let raw = load_ay_fixture("noise_lfsr");
    let fixture: NoiseLfsrFixture =
        serde_json::from_str(&raw).expect("parse noise_lfsr.json");

    let mut seed = fixture.initial_seed;
    for (i, expected) in fixture.steps.iter().enumerate() {
        seed = noise_generator(seed);
        // noise_val = bit16 of seed (from the original Delphi union layout)
        let noise_val = (seed >> 16) & 1;
        assert_eq!(
            seed, expected.seed,
            "step {}: seed mismatch (got {:#x}, want {:#x})",
            i, seed, expected.seed
        );
        assert_eq!(
            noise_val, expected.noise_val,
            "step {}: noise_val mismatch (got {}, want {})",
            i, noise_val, expected.noise_val
        );
    }
}

// ─── Envelope shapes ─────────────────────────────────────────────────────────

/// Verify all 8 envelope shapes produce the correct 64-step amplitude sequences.
#[test]
fn envelope_shapes_match_pascal_baseline() {
    let raw = load_ay_fixture("envelope_shapes");
    let fixture: EnvelopeShapesFixture =
        serde_json::from_str(&raw).expect("parse envelope_shapes.json");

    for case in &fixture.shapes {
        let mut chip = SoundChip::default();
        chip.set_envelope_register(case.register_value);
        assert_eq!(
            chip.envelope_step, case.initial_ampl,
            "shape {}: initial ampl mismatch (got {}, want {})",
            case.name, chip.envelope_step, case.initial_ampl
        );

        for (i, expected) in case.steps.iter().enumerate() {
            chip.step_envelope();
            assert_eq!(
                chip.envelope_step, expected.ampl,
                "shape {} step {}: ampl mismatch (got {}, want {})",
                case.name, i, chip.envelope_step, expected.ampl
            );
            assert_eq!(
                chip.first_period, expected.first_period,
                "shape {} step {}: first_period mismatch (got {}, want {})",
                case.name, i, chip.first_period, expected.first_period
            );
        }
    }
}

/// Sanity-check: envelope shape register mapping matches Pascal.
#[test]
fn envelope_shape_from_register_matches_baseline() {
    let raw = load_ay_fixture("envelope_shapes");
    let fixture: EnvelopeShapesFixture =
        serde_json::from_str(&raw).expect("parse envelope_shapes.json");

    let expected_shapes: &[(u8, EnvShape)] = &[
        (0,  EnvShape::Hold0),
        (4,  EnvShape::Hold31),
        (8,  EnvShape::Saw8),
        (10, EnvShape::Triangle10),
        (11, EnvShape::DecayHold),
        (12, EnvShape::Saw12),
        (13, EnvShape::AttackHold),
        (14, EnvShape::Triangle14),
    ];
    for (case, &(reg, ref expected)) in fixture.shapes.iter().zip(expected_shapes.iter()) {
        assert_eq!(
            case.register_value, reg,
            "fixture ordering mismatch for {}",
            case.name
        );
        assert_eq!(
            EnvShape::from_register(reg),
            *expected,
            "shape mismatch for register {}",
            reg
        );
    }
}

// ─── Level tables ─────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct LevelTablesFixture {
    cases: Vec<LevelTableCase>,
}

#[derive(Deserialize)]
struct LevelTableCase {
    name: String,
    chip: String,
    index_al: u8,
    index_ar: u8,
    index_bl: u8,
    index_br: u8,
    index_cl: u8,
    index_cr: u8,
    al: Vec<i32>,
    ar: Vec<i32>,
    bl: Vec<i32>,
    br: Vec<i32>,
    cl: Vec<i32>,
    cr: Vec<i32>,
}

/// Verify that `calculate_level_tables` produces bit-identical output to the
/// Pascal `Calculate_Level_Tables` in `digsoundbuf.pas`.
///
/// This test covers:
/// - Stereo AY with default panning (A=255/13, B=170/170, C=13/255)
/// - Stereo YM with the same default panning
///
/// Regressions caught: missing `* 2` on the `l` normalisation denominator,
/// and the two-step rounding that caused every entry to be ~2× too large.
#[test]
fn level_tables_match_pascal_baseline() {
    let raw = load_ay_fixture("level_tables");
    let fixture: LevelTablesFixture =
        serde_json::from_str(&raw).expect("parse level_tables.json");

    for case in &fixture.cases {
        let chip_type = match case.chip.as_str() {
            "AY" => ChipType::AY,
            "YM" => ChipType::YM,
            other => panic!("unknown chip type: {}", other),
        };

        let cfg = AyConfig {
            index_al: case.index_al,
            index_ar: case.index_ar,
            index_bl: case.index_bl,
            index_br: case.index_br,
            index_cl: case.index_cl,
            index_cr: case.index_cr,
            global_volume: 1.0,
            global_volume_max: 1.0,
            ..AyConfig::default()
        };

        let t = calculate_level_tables(&cfg, chip_type);

        let check = |table: &[i32; 32], expected: &Vec<i32>, name: &str| {
            for (i, (&got, &want)) in table.iter().zip(expected.iter()).enumerate() {
                assert_eq!(
                    got, want,
                    "case '{}' table '{}' index {}: got {}, want {}",
                    case.name, name, i, got, want
                );
            }
        };

        check(&t.al, &case.al, "al");
        check(&t.ar, &case.ar, "ar");
        check(&t.bl, &case.bl, "bl");
        check(&t.br, &case.br, "br");
        check(&t.cl, &case.cl, "cl");
        check(&t.cr, &case.cr, "cr");
    }
}

// ─── Mono mixer ──────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct MixerMonoFixture {
    cases: Vec<MixerMonoCase>,
}

#[derive(Deserialize)]
struct MixerMonoCase {
    name: String,
    level: i32,
    ampl_a: u8,
    ampl_b: u8,
    ampl_c: u8,
    ampl_env: i32,
    ton_en_a: bool,
    ton_en_b: bool,
    ton_en_c: bool,
    noise_en_a: bool,
    noise_en_b: bool,
    noise_en_c: bool,
    ton_a: i32,
    ton_b: i32,
    ton_c: i32,
    noise_val: u32,
    env_en_a: bool,
    env_en_b: bool,
    env_en_c: bool,
}

/// Verify that `synthesizer_mixer_q_mono` produces bit-identical output to the
/// Pascal `TSoundChip.Synthesizer_Mixer_Q_Mono` across 6 representative chip states.
///
/// The fixture uses the default AY stereo panning (A=255/13, B=170/170, C=13/255)
/// to build the level tables, and tests: single-channel fixed, multi-channel fixed,
/// envelope mode, tone-zero silence, noise-AND-gate silence, and noise passthrough.
#[test]
fn mixer_mono_matches_pascal_baseline() {
    let raw = load_ay_fixture("mixer_mono");
    let fixture: MixerMonoFixture =
        serde_json::from_str(&raw).expect("parse mixer_mono.json");

    let cfg = AyConfig {
        index_al: 255,
        index_ar: 13,
        index_bl: 170,
        index_br: 170,
        index_cl: 13,
        index_cr: 255,
        global_volume: 1.0,
        global_volume_max: 1.0,
        ..AyConfig::default()
    };
    let t = calculate_level_tables(&cfg, ChipType::AY);

    for case in &fixture.cases {
        let mut chip = SoundChip::default();
        // Amplitude registers: set_ampl_* derives envelope_en flag
        chip.set_ampl_a(case.ampl_a);
        chip.set_ampl_b(case.ampl_b);
        chip.set_ampl_c(case.ampl_c);
        // Override envelope_en flags to match fixture (fixture uses inverted convention)
        chip.envelope_en_a = case.env_en_a;
        chip.envelope_en_b = case.env_en_b;
        chip.envelope_en_c = case.env_en_c;
        // Tone / noise mixer gates
        chip.ton_en_a   = case.ton_en_a;
        chip.ton_en_b   = case.ton_en_b;
        chip.ton_en_c   = case.ton_en_c;
        chip.noise_en_a = case.noise_en_a;
        chip.noise_en_b = case.noise_en_b;
        chip.noise_en_c = case.noise_en_c;
        // Tone square-wave outputs and noise LFSR output
        chip.ton_a    = case.ton_a;
        chip.ton_b    = case.ton_b;
        chip.ton_c    = case.ton_c;
        chip.noise_val = case.noise_val;
        // Envelope amplitude step
        chip.envelope_step = case.ampl_env;

        let mut level = 0i32;
        chip.synthesizer_mixer_q_mono(&t.al, &t.bl, &t.cl, &mut level);

        assert_eq!(
            level, case.level,
            "case '{}': level mismatch (got {}, want {})",
            case.name, level, case.level
        );
    }
}
