//! Approval / baseline tests for `vti-ay` against Pascal-generated fixtures.
//!
//! Each test loads a committed JSON fixture from
//! `tests/fixtures/pascal-baselines/` and asserts that the Rust
//! implementation produces bit-identical output.
//!
//! The fixtures were generated by running
//!   `bash pascal-tests/run_harness.sh`
//! which compiles `pascal-tests/vt_harness.pas` (FPC) and outputs JSON.
//! That Pascal code is a faithful port of S.V.Bulba's original AY.pas.
//!
//! HOW TO REGENERATE
//! -----------------
//! 1. Install fpc (Free Pascal ≥ 3.x).
//! 2. Run:  bash pascal-tests/run_harness.sh
//! 3. Review the diff and commit the updated fixtures.
//!
//! A change in a fixture file that was NOT caused by a deliberate Pascal
//! source change is a regression — investigate before merging.

use serde::Deserialize;
use vti_ay::chip::{noise_generator, EnvShape, SoundChip};

// ─── Fixture types ────────────────────────────────────────────────────────────

#[derive(Deserialize)]
struct NoiseLfsrFixture {
    initial_seed: u32,
    steps: Vec<NoiseLfsrStep>,
}

#[derive(Deserialize)]
struct NoiseLfsrStep {
    seed: u32,
    noise_val: u32,
}

#[derive(Deserialize)]
struct EnvelopeShapesFixture {
    shapes: Vec<EnvelopeShapeCase>,
}

#[derive(Deserialize)]
struct EnvelopeShapeCase {
    register_value: u8,
    name: String,
    initial_ampl: i32,
    steps: Vec<EnvelopeStep>,
}

#[derive(Deserialize)]
struct EnvelopeStep {
    ampl: i32,
    first_period: bool,
}

// ─── Helper ──────────────────────────────────────────────────────────────────

fn load_ay_fixture(name: &str) -> String {
    let path = format!(
        "{}/tests/fixtures/pascal-baselines/{}.json",
        env!("CARGO_MANIFEST_DIR"),
        name
    );
    std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("Cannot read fixture {}: {}", path, e))
}

// ─── Noise LFSR ──────────────────────────────────────────────────────────────

/// Verify that the Rust LFSR produces the same 200-step sequence as the Pascal.
///
/// The Pascal NoiseGenerator uses taps bit13 XOR bit16 of the 17-bit seed.
/// noise_val is bit16 of the resulting seed (from the packed-record union
/// layout in the original TSoundChip).
#[test]
fn noise_lfsr_matches_pascal_baseline() {
    let raw = load_ay_fixture("noise_lfsr");
    let fixture: NoiseLfsrFixture =
        serde_json::from_str(&raw).expect("parse noise_lfsr.json");

    let mut seed = fixture.initial_seed;
    for (i, expected) in fixture.steps.iter().enumerate() {
        seed = noise_generator(seed);
        // noise_val = bit16 of seed (from the original Delphi union layout)
        let noise_val = (seed >> 16) & 1;
        assert_eq!(
            seed, expected.seed,
            "step {}: seed mismatch (got {:#x}, want {:#x})",
            i, seed, expected.seed
        );
        assert_eq!(
            noise_val, expected.noise_val,
            "step {}: noise_val mismatch (got {}, want {})",
            i, noise_val, expected.noise_val
        );
    }
}

// ─── Envelope shapes ─────────────────────────────────────────────────────────

/// Verify all 8 envelope shapes produce the correct 64-step amplitude sequences.
#[test]
fn envelope_shapes_match_pascal_baseline() {
    let raw = load_ay_fixture("envelope_shapes");
    let fixture: EnvelopeShapesFixture =
        serde_json::from_str(&raw).expect("parse envelope_shapes.json");

    for case in &fixture.shapes {
        let mut chip = SoundChip::default();
        chip.set_envelope_register(case.register_value);
        assert_eq!(
            chip.ampl, case.initial_ampl,
            "shape {}: initial ampl mismatch (got {}, want {})",
            case.name, chip.ampl, case.initial_ampl
        );

        for (i, expected) in case.steps.iter().enumerate() {
            chip.step_envelope();
            assert_eq!(
                chip.ampl, expected.ampl,
                "shape {} step {}: ampl mismatch (got {}, want {})",
                case.name, i, chip.ampl, expected.ampl
            );
            assert_eq!(
                chip.first_period, expected.first_period,
                "shape {} step {}: first_period mismatch (got {}, want {})",
                case.name, i, chip.first_period, expected.first_period
            );
        }
    }
}

/// Sanity-check: envelope shape register mapping matches Pascal.
#[test]
fn envelope_shape_from_register_matches_baseline() {
    let raw = load_ay_fixture("envelope_shapes");
    let fixture: EnvelopeShapesFixture =
        serde_json::from_str(&raw).expect("parse envelope_shapes.json");

    let expected_shapes: &[(u8, EnvShape)] = &[
        (0,  EnvShape::Hold0),
        (4,  EnvShape::Hold31),
        (8,  EnvShape::Saw8),
        (10, EnvShape::Triangle10),
        (11, EnvShape::DecayHold),
        (12, EnvShape::Saw12),
        (13, EnvShape::AttackHold),
        (14, EnvShape::Triangle14),
    ];
    for (case, &(reg, ref expected)) in fixture.shapes.iter().zip(expected_shapes.iter()) {
        assert_eq!(
            case.register_value, reg,
            "fixture ordering mismatch for {}",
            case.name
        );
        assert_eq!(
            EnvShape::from_register(reg),
            *expected,
            "shape mismatch for register {}",
            reg
        );
    }
}
